apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhokp-mcp-server
  namespace: rhokp-server
  labels:
    app: rhokp-mcp
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhokp-mcp-server
  namespace: rhokp-server
  labels:
    app: rhokp-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhokp-mcp
  template:
    metadata:
      labels:
        app: rhokp-mcp
    spec:
      serviceAccountName: rhokp-mcp-server
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: rhokp-mcp
      containers:
      - name: rhokp-mcp
        #image: quay.io/danclark/okp-mcp:latest # Old copy before move
        image: quay.io/redhat-user-workloads/rhel-lightspeed-tenant/rhel-knowledge-bridge:latest
        env:
        - name: MCP_TRANSPORT
          value: streamable-http
        - name: MCP_SOLR_URL
          value: "http://rhokp-server.rhokp-server.svc.cluster.local:8983"
        - name: MCP_LOG_LEVEL
          value: "INFO"
        #livenessProbe:
        #  tcpSocket:
        #    port: 8000
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
        #  failureThreshold: 3
        #readinessProbe:
        #  tcpSocket:
        #    port: 8000
        #  initialDelaySeconds: 5
        #  periodSeconds: 10
        #  failureThreshold: 3
        ports:
        - name: mcp
          containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rhokp-mcp
  name: rhokp-mcp
  namespace: rhokp-server
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: rhokp-mcp
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: rhokp-mcp
  name: rhokp-mcp
  namespace: rhokp-server
spec:
  port:
    targetPort: 8000
  to:
    kind: Service
    name: rhokp-mcp
    weight: 100
  wildcardPolicy: None
